def create_graph(graph):
    # adding vertices
    graph.add_vertex('A', (100, 100))
    graph.add_vertex('B', (300, 100))
    graph.add_vertex('C', (500, 100))
    graph.add_vertex('D', (700, 100))
    graph.add_vertex('E', (900, 100))
    graph.add_vertex('F', (100, 300))
    graph.add_vertex('G', (900, 300))
    graph.add_vertex('H', (100, 400))
    graph.add_vertex('I', (900, 400))
    graph.add_vertex('J', (100, 600))
    graph.add_vertex('K', (300, 600))
    graph.add_vertex('L', (500, 600))
    graph.add_vertex('M', (700, 600))
    graph.add_vertex('N', (900, 600))
    graph.add_vertex('O', (500, 300))
    graph.add_vertex('P', (500, 400))

    # adding bidirectional edges
    graph.add_edge('A', 'B', 1, True)
    graph.add_edge('B', 'C', 1, True)
    graph.add_edge('C', 'D', 1, True)
    graph.add_edge('D', 'E', 1, True)
    graph.add_edge('J', 'K', 1, True)
    graph.add_edge('K', 'L', 1, True)
    graph.add_edge('L', 'M', 1, True)
    graph.add_edge('M', 'N', 1, True)
    graph.add_edge('A', 'F', 1, True)
    graph.add_edge('F', 'A', 1, True)
    graph.add_edge('G', 'E', 1, True)
    graph.add_edge('E', 'G', 1, True)
    graph.add_edge('H', 'J', 1, True)
    graph.add_edge('J', 'H', 1, True)
    graph.add_edge('I', 'N', 1, True)
    graph.add_edge('N', 'I', 1, True)
    graph.add_edge('O', 'P', 1, True)

    # adding single direction edges
    graph.add_edge('F', 'O', 1, False)
    graph.add_edge('O', 'G', 1, False)
    graph.add_edge('I', 'P', 1, False)
    graph.add_edge('P', 'H', 1, False)
